/* TerraIntel v4 - working map with NASA GIBS and interactive NASA POWER fetch */
var map = L.map('mapid', {preferCanvas:true}).setView([21.0285, 105.8542], 8);
var osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {maxZoom: 19, attribution: '&copy; OpenStreetMap contributors'}).addTo(map);
function gibsLayer(layerName, date){ date = date || '2023-07-01'; var url = 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/' + layerName + '/default/' + date + '/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg'; return L.tileLayer(url, {maxZoom: 9, attribution: 'NASA GIBS'}); }
var trueColor = gibsLayer('MODIS_Terra_CorrectedReflectance_TrueColor','2023-07-01');
var viirsNight = gibsLayer('VIIRS_SNPP_CityLights_2012','2012-01-01');
var lst = gibsLayer('MODIS_Terra_L3_Land_Surface_Temp_Day','2023-07-01');
var overlays = { 'MODIS True Color': trueColor, 'VIIRS Night Lights': viirsNight, 'MODIS LST (demo)': lst };
L.control.layers({'OpenStreetMap': osm}, overlays, {collapsed:false}).addTo(map);
L.control({position:'bottomright'}).onAdd = function(){ var div = L.DomUtil.create('div','legend-box'); div.innerHTML = '<div style="background:#07121a;padding:8px;border-radius:6px;color:#e6f0f6"><strong>TerraIntel Layers</strong><br><small>Toggle satellite layers</small></div>'; return div; };
document.getElementById('kpi-prec').innerText='Loading...'; document.getElementById('kpi-temp').innerText='Loading...'; document.getElementById('kpi-solar').innerText='Loading...';
function renderPowerChart(labels, t2m, solar){ var powerCtx = document.getElementById('powerChart').getContext('2d'); if(window.powerChart) window.powerChart.destroy(); window.powerChart = new Chart(powerCtx, { type:'line', data:{ labels: labels, datasets:[{label:'Temperature (T2M, °C)', data:t2m, yAxisID:'y1', borderColor:'#ff9f43', backgroundColor:'rgba(255,159,67,0.08)', fill:true, tension:0.2},{label:'Solar Radiation (MJ/m²/day)', data:solar, yAxisID:'y2', borderColor:'#00d1ff', backgroundColor:'rgba(0,209,255,0.08)', fill:true, tension:0.2}] }, options:{ plugins:{legend:{labels:{color:'#cfeffb'}}}, scales:{ x:{ticks:{color:'#cfeffb'}}, y1:{type:'linear',position:'left',ticks:{color:'#ffb78a'},title:{display:true,text:'T2M (°C)',color:'#ffb78a'}}, y2:{type:'linear',position:'right',ticks:{color:'#9fe7ff'},grid:{drawOnChartArea:false},title:{display:true,text:'Solar (MJ/m²/day)',color:'#9fe7ff'}} } } }); }
function fetchPOWER_point(lat, lon){ var url = 'https://power.larc.nasa.gov/api/temporal/climatology/point?parameters=T2M,ALLSKY_SFC_SW_DWN&community=AG&longitude=' + lon + '&latitude=' + lat + '&format=JSON'; fetch(url).then(r=>r.json()).then(data=>{ try{ var t2m = data.parameters.T2M; var solar = data.parameters.ALLSKY_SFC_SW_DWN; var labels = Object.keys(t2m).map(m=>'M'+m); var t2m_vals = Object.values(t2m).map(v => Math.round((v-273.15)*10)/10 ); var solar_vals = Object.values(solar).map(v => Math.round(v*10)/10); document.getElementById('kpi-prec').innerText = 'See charts'; document.getElementById('kpi-temp').innerText = (Math.round((t2m_vals.reduce((a,b)=>a+b,0)/t2m_vals.length)*10)/10) + ' °C'; document.getElementById('kpi-solar').innerText = (Math.round((solar_vals.reduce((a,b)=>a+b,0)/solar_vals.length)*10)/10) + ' MJ/m²/day'; renderPowerChart(labels, t2m_vals, solar_vals); }catch(e){ console.error('POWER parse error', e); alert('POWER data not available for this location.'); } }).catch(e=>{ console.error('POWER fetch error', e); alert('Failed to fetch POWER data.'); }); }
fetchPOWER_point(21.0285, 105.8542);
map.on('click', function(e){ var lat = e.latlng.lat.toFixed(4), lon = e.latlng.lng.toFixed(4); fetchPOWER_point(lat, lon); L.popup().setLatLng(e.latlng).setContent('<strong>TerraIntel</strong><br>Fetching POWER data for: ' + lat + ', ' + lon).openOn(map); });
new Chart(document.getElementById('chartGrowth').getContext('2d'), {type:'line', data:{labels:['2000','2005','2010','2015','2020','2023'], datasets:[{label:'Urban area (km²)', data:[120,180,250,340,420,480], borderColor:'#00d1ff', backgroundColor:'rgba(0,209,255,0.12)', fill:true}]}, options:{plugins:{legend:{display:false}}}});
new Chart(document.getElementById('chartNightPop').getContext('2d'), {type:'scatter', data:{datasets:[{label:'City sectors', data:[{x:10,y:2000},{x:30,y:8000},{x:50,y:12000},{x:70,y:22000},{x:90,y:40000}], backgroundColor:'#ffb86b'}]}, options:{plugins:{legend:{display:false}}, scales:{x:{title:{display:true,text:'Nightlight intensity'}, ticks:{color:'#cfeffb'}}, y:{title:{display:true,text:'Population'}, ticks:{color:'#cfeffb'}}}}});
new Chart(document.getElementById('chartNDVI').getContext('2d'), {type:'line', data:{labels:['2018','2019','2020','2021','2022','2023'], datasets:[{label:'NDVI (mean)', data:[0.45,0.48,0.46,0.50,0.52,0.53], borderColor:'#7cffb2', backgroundColor:'rgba(124,255,178,0.12)', fill:true}]}, options:{plugins:{legend:{display:false}}}});
